repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-yaml
        name: Check YAML files
      - id: trailing-whitespace
        name: Trim Trailing Whitespaces
  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
        name: Reformatting with Black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        name: Check Ruff
  - repo: https://github.com/python-poetry/poetry
    rev: "1.6.0"
    hooks:
      - id: poetry-check
        stages: [push]
        name: Check Poetry environment
      - id: poetry-lock
        name: Lock Dependencies with Poetry
        stages: [push]
      - id: poetry-export
        name: Export Dependencies with Poetry
        args:
          ["--without=dev", "-f", "requirements.txt", "-o", "requirements.txt"]
        stages: [push]
      - id: poetry-export
        name: Export Dev Dependencies with Poetry
        args:
          [
            "--with=dev",
            "--extras=all",
            "-f",
            "requirements.txt",
            "-o",
            "requirements-dev.txt",
          ]
        stages: [push]
